[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-6.0/lib/libclang.so.1'
let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
let g:deoplete#enable_at_startup = 1
'''
on_i = 1

#[[plugins]]
#repo = 'Shougo/deoppet.nvim'
#

#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = 'python'

[[plugins]]
repo = 'zchee/deoplete-clang'
on_ft = ['c','cc', 'cpp', 'cmake']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
depends = ['deoplete.nvim']
